Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'codebreaker.gemspec'
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
